name: Build and Deploy Notes (HTML + PDF)

on:
  push:
    branches: ["main"]
    paths:
      - 'tex/*.tex'
      - 'scripts/**'
      - '.github/workflows/build-and-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  compile-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full pandoc

      - name: Create output folder
        run: mkdir -p site

      - name: Build HTML files with Pandoc + Lua filter
        run: |
          for f in tex/*.tex; do
            fname=$(basename "$f" .tex)
            pandoc "$f" \
              --lua-filter=scripts/tufte.lua \
              -s \
              --css=tufte.css \
              -o "site/${fname}.html"
          done
          cp tufte.css site/

      - name: Copy PDFs to site
        run: |
          mkdir -p site/pdf
          cp tex/*.pdf site/pdf/

      - name: Copy figures to site
        run: cp -r tex/figures site/

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: site
          base-url-path: https://bridgeslab.github.io/MolecularNutrition/
          include-html: true
          include-pdf: false
        env:
          SITEMAP_OUTPUT_PATH: site/sitemap.xml

  deploy-pages:
    needs: compile-site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
