name: Build and Deploy Notes (HTML + PDF)

on:
  push:
    branches: ["main"]
    paths:
      - 'tex/*.tex'
      - 'scripts/**'
      - '.github/workflows/build-and-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full pandoc

      - name: Create output folders
        run: |
          mkdir -p html
          mkdir -p pdf

      - name: Build HTML files with Pandoc + Lua filter
        run: |
          for f in tex/*.tex; do
            fname=$(basename "$f" .tex)
            pandoc "$f" \
              --lua-filter=scripts/tufte.lua \
              -s \
              --css=tufte.css \
              -o "html/${fname}.html"
          done

      - name: Build PDF files
        run: |
          for f in tex/*.tex; do
            fname=$(basename "$f" .tex)
            cd tex
            pdflatex -interaction=nonstopmode -halt-on-error -output-directory=../pdf "$fname.tex" || exit 1
            pdflatex -interaction=nonstopmode -halt-on-error -output-directory=../pdf "$fname.tex" || exit 1
            cd ..
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: './html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > html/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> html/sitemap.xml
          for file in html/*.html; do
            fname=$(basename "$file")
            url="https://bridgeslab.github.io/MolecularNutrition/$fname"
            mod_date=$(git log -1 --format="%cI" "tex/${fname%.html}.tex" 2>/dev/null || date -I)
            echo "  <url>" >> html/sitemap.xml
            echo "    <loc>$url</loc>" >> html/sitemap.xml
            echo "    <lastmod>$mod_date</lastmod>" >> html/sitemap.xml
            echo "  </url>" >> html/sitemap.xml
          done
          echo '</urlset>' >> html/sitemap.xml
