name: Build and Deploy Notes (HTML + PDF)

on:
  push:
    paths:
      - 'tex/*.tex'
      - 'scripts/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full pandoc

      - name: Create output folders
        run: |
          mkdir -p html
          mkdir -p pdf

      - name: Build HTML files with Pandoc + Lua filter
        run: |
          for f in tex/*.tex; do
            fname=$(basename "$f" .tex)
            pandoc "$f" \
              --lua-filter=scripts/tufte.lua \
              -s \
              --css=tufte.css \
              -o "html/${fname}.html"
          done

      - name: Build PDF files
        run: |
            mkdir -p pdf
            for f in tex/*.tex; do
              fname=$(basename "$f" .tex)
              cd tex
              pdflatex -interaction=nonstopmode -halt-on-error -output-directory=../pdf "$fname.tex" || exit 1
              pdflatex -interaction=nonstopmode -halt-on-error -output-directory=../pdf "$fname.tex" || exit 1
              cd ..
            done

      - name: Deploy to GitHub Pages
        run: |
          # Set up Git for deployment
          git config --global user.email "dave.bridges@gmail.com"
          git config --global user.name "Dave Bridges"
          
          # Create a new branch 'gh-pages'
          git checkout --orphan gh-pages
          git rm -rf .

          # Copy the generated HTML to the gh-pages branch
          cp -R html/* .

          # Add and commit the changes
          git add .
          git commit -m "Deploy HTML files"

          # Push to gh-pages branch
          git push -f origin gh-pages

      - name: Upload HTML and PDF as artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: built-files
          path: |
            html/
            pdf/
  