name: Build and Deploy Notes (HTML + PDF)

on:
  push:
    branches: ["main"]
    paths:
      - 'tex/*.tex'
      - 'scripts/**'
      - 'html/index.html'
      - 'html/tufte.css'
      - '.github/workflows/build-and-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full pandoc

      - name: Create output directory
        run: mkdir -p output/pdf output/figures

      - name: Compile HTML from .tex
        run: |
          for f in tex/*.tex; do
            fname=$(basename "$f" .tex)
            pandoc "$f" \
              --lua-filter=scripts/tufte.lua \
              -s \
              --css=tufte.css \
              --mathjax \
              --citeproc \
              --bibliography=tex/library.bib \
              -o "output/${fname}.html"
          done

      - name: Copy PDFs
        run: cp tex/*.pdf output/pdf/

      - name: Copy figures
        run: cp -r tex/figures/* output/figures/ || true

      - name: Copy tufte.css
        run: cp html/tufte.css output/

      - name: Copy custom index.html
        run: cp html/index.html output/

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
