name: Build and Deploy Notes (HTML + PDF)

on:
  push:
    branches: ["main"]
    paths:
      - 'tex/*.tex'
      - 'scripts/**'
      - '.github/workflows/build-and-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  compile-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full pandoc
      - name: Create output folder
        run: mkdir -p html
      - name: Build HTML files with Pandoc + Lua filter
        run: |
          for f in tex/*.tex; do
            fname=$(basename "$f" .tex)
            pandoc "$f" \
              --lua-filter=scripts/tufte.lua \
              -s \
              --css=tufte.css \
              -o "html/${fname}.html"
          done
      - name: Copy existing PDFs to HTML folder
        run: |
          mkdir -p html/pdf
          cp tex/*.pdf html/pdf/
      - name: Copy figures to HTML folder
        run: cp -r tex/figures html/

  generate-sitemap:
    needs: compile-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: html
          base-url-path: https://bridgeslab.github.io/MolecularNutrition/
          include-html: true
          include-pdf: false
        env:
          SITEMAP_OUTPUT_PATH: html/sitemap.xml
      - name: Fix sitemap.xml ownership
        run: sudo chown runner:docker html/sitemap.xml

  deploy-pages:
    needs: generate-sitemap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: './html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  push-pdf-update:
    needs: deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update PDFs" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PDF_BUILD }}@github.com/${{ github.repository }}.git main
